### PR TITLE
Add Validation on Auth Pages

### PR DESCRIPTION
**Pull request by AkashSharma001**

### CODE REVIEW

**Comment by AkashSharma001** [comment]
> 10:47:36 PM: build-image version: 4c0c1cadee6a31c9bb8d824514030009c4c05c6a (focal)
10:47:36 PM: build-image tag: v4.15.0
10:47:36 PM: buildbot version: b667c0cf0472892d6662aeba3d9a940e2b5df93d
10:47:36 PM: Fetching cached dependencies
10:47:36 PM: Starting to download cache of 163.0MB
10:47:38 PM: Finished downloading cache in 1.592126948s
10:47:38 PM: Starting to extract cache
10:47:40 PM: Finished extracting cache in 2.406460119s
10:47:40 PM: Finished fetching cache in 4.033536835s
10:47:40 PM: Starting to prepare the repo for build
10:47:40 PM: **git ref pull/234/head does not exist or you do not have permission**
10:47:40 PM: Creating deploy upload records
10:47:40 PM: Failing build: Failed to prepare repo
10:47:40 PM: **Failed during stage 'preparing repo': git ref pull/234/head does not exist**
10:47:41 PM: Finished processing build request in 4.682467077s
>
Above Netlify Log.
In the log, Netlify doesn't find my repo @shelcia 
Could please re-Trigger for deployment?
Because I have checked and there is no error in the deployment.

**Comment by AkashSharma001** [comment]
https://user-images.githubusercontent.com/97700368/207405880-9dace20d-b789-4d9d-bf76-c906ec65010d.mp4

**Comment by shelcia** [comment]
I re-ran it was still failing

**Comment by AkashSharma001** [comment]
> I re-ran it was still failing
@shelcia 
Could you please give me the deployment log when you re-run?

I don't know what's happening with your deployment. When I deployed, I didn't get any errors. As you have shown in the above video.

**Pull request closed without merging**
