### PR TITLE
Auto-recognize embedded links and tag them appropriately

### LINKED ISSUE #6: Users should be able to embed links(maybe a gist, medium article or youtube video) in their post

### PR DESCRIPTION
**Pull request by paramsiddharth**
# Auto-recognize embedded links and tag them appropriately
Resolves #6: **Users should be able to embed links(maybe a gist, medium article or youtube video) in their post**

## Modifications
- Replace `ReactEmoji.emojify` inside the Post component with a custom function.
  ``` jsx
  <h3 className="mb-3">{addLinks(post.title)}</h3>
  ```
- Define a function to match URLs and tag them appropriately. All text blocks processed by the function will be `ReactEmoji.emojify`ed to retain the style.
  ``` jsx
  const addLinks = (postText) => {
    ...
    if (block.match(urlRegexp)) {
      return (
        <React.Fragment key={i}>
          <a href={block} target='_blank' rel='noopener noreferrer'>
            {ReactEmoji.emojify(block)}
          </a>
        </React.Fragment>
      );
    } else {
      return (
        <React.Fragment key={i}>
          {ReactEmoji.emojify(block)}
        </React.Fragment>
      );
    }
    ...
  };
  ```

# Notes
- `ReactEmoji.emojify` doesn't return raw text and had to be used separately after the processing of links.
- Future removal of the `addLinks` from the component and storing and importing it from a separate `custom-modules` or `services` folder would be suggested to clean-up the component code.

## Demonstration
The posts were done on the Heroku server and not locally.
image
image
image

### CODE REVIEW

**Review by shelcia — CHANGES_REQUESTED** [review]
please work on the links

**Comment by paramsiddharth** [comment]
> please work on the links

@shelcia Pardon? Please clarify what I need to do. Now that there is a merge conflict, I definitely need to resolve that too.

**Comment by shelcia** [comment]
Please resolve the conflicts

**Comment by paramsiddharth** [comment]
> Please resolve the conflicts

Done. Please review the update. I have provided all the modification details within the PR.

**Review by shelcia — APPROVED** [review]

**Pull request merged**
