### PR TITLE
disable multiple likes/dislikes

### PR DESCRIPTION
**Pull request by Chaitanya31612**
Fixed this issue.

### CODE REVIEW

**Comment by Chaitanya31612** [comment]
@shelcia can you please try running it locally, I don't know why the tests are failing.

**Comment by shelcia** [comment]
All deploy check are failed and what will happen if user logouts .. most local storage is preferred to be cleared out after logging out

**Comment by Chaitanya31612** [comment]
> All deploy check are failed and what will happen if user logouts .. most local storage is preferred to be cleared out after logging out

Actually, the best approach I can think of is instead of storing likes count in the database an array of userids should be stored and their count should be used instead. By this, no duplicate would be there and an accurate count can be displayed. But it will require changes in the backend as well and some refactoring of previously written code also. This was the solution I can think of although I very well know this is not that robust.

**Review by shelcia — CHANGES_REQUESTED** [review]
The backend link in attached in readme you can work with that

**Pull request closed without merging**
